guest:
  default: false
  
  session:
    add: true
    create: true
  
  
user:
  inherit_from: guest
  
  session:
    delete: true
  
  
vip:
  inherit_from: user


trail-gm:
  default: true
  
  accounts:
    edit: false
    update: false

  characters:
    edit: false
    update: false
    transfer: false
    write_dump: false
    load_dump: false
    erase: false
    
  accountacl: false


gm:
  default: true
  
  characters:
    transfer: false
    write_dump: false
    load_dump: false
    erase: false
  
  accountacl: false
  
  
lead-gm:
  default: true