guest:
  default: false
  
  session:
    add: true
    create: true
  
  
user:
  inherit_from: guest
  
  session:
    delete: true
  
  
vip:
  inherit_from: user


trail-gm:
  default: true
  
  accounts:
    edit: false
    update: false
  characters:
    edit: false
    update: false


gm:
  inherit_from: vip
  default: true
  
  accountacl:
    edit: false
    update: false
    add: false
    create: false
  
lead-gm:
  inherit_from: gm
  
  accountacl:
    edit: true
    update: true
    add: true
    create: true
    delete: true