guest:
  default: false
  
  session:
    add: true
    create: true
  
  
user:
  inherit_from: guest
  
  session:
    delete: true
  
  
vip:
  inherit_from: user


trail-gm:
  default: true
  
  accounts:
    edit: false
    update: false

  characters:
    edit: false
    update: false
    transfer: false
    write_dump: false
    load_dump: false
    copy: false
    erase: false
    recover: false
    
  accountacl: false
  
  comments:
    delete: false

  motd:
    edit: false
    
  premium_codes:
    reactivate: false

gm:
  inherit_from: trail-gm
  
  accounts:
    edit: true
    update: true
  
  characters:
    edit: true
    update: true
  
lead-gm:
  default: true
